### ISSUE TITLE
add reviews to homepage?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#10]
links to reviews on the bottom of the home page would be good I think. Perhaps some key quotes even from the reviews selling the game.

**Comment by williamdekryger** [comment]
Ok, here are the reviews I know of:

- [Chip review of TripleA] (http://download.chip.eu/en/TripleA_175255.html)
- [ModDB review] (http://www.moddb.com/games/triplea/downloads/windows-installer-without-java)
- [BrotherSoft review] (http://games.brothersoft.com/triplea-for-linux.html)
- [SoftFiles review] (http://www.soft-files.com/game/triplea-with-java_1415.html)
- [CNet TripleA review] (http://download.cnet.com/TripleA/3000-18516_4-75184098.html?tag=mncol%3B1)
- [FreeWareGenius Open Source Turn-Based Strategy Game Roundup] (http://www.freewaregenius.com/an-overview-of-free-turn-based-strategy-and-war-games/)
- [Appcolt review] (http://games.appcolt.com/full-download-game/5611-triplea-with-java.html)

Any others I missed?

**Comment by DanVanAtta** [comment]
The review links would be very good in an about page or something similar. On the home page I'm thinking we could have some screen grabs and/or quotes from some of the selected reviews.

**Comment by DanVanAtta** [comment]
mothballing, we have higher priorities to work on.
