### ISSUE TITLE
Download links broken...

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea-game.github.io#102]
... because the file versions have not been updated (still 3057 instead of 3089):

For example
https://github.com/triplea-game/triplea/releases/download/1.9.0.0.3089/TripleA_1.9.0.0.3057_windows-64bit.exe

So a 404 error results.

**Comment by DanVanAtta** [comment]
Should be fixed now with: https://github.com/triplea-game/triplea-game.github.io/pull/103

**Comment by panther2** [comment]
Fixed and closed, thanks.
