### ISSUE TITLE
Pages to be moved to Documentation Folder

### ISSUE THREAD

**Issue by williamdekryger** [triplea-game/triplea-game.github.io#109]
On the site, we have a few pages that definitely fall into the category of documentation. A few come to mind, including, "bug_report," "upgrade_notes," and "release_notes." Is it a possibility to have those put under the `docs/` folder, as this would facilitate the expansion of documentation in that location later on? I propose we move those to the docs folder for the time being, knowing that there will be a general push to see more of our documentation relocated to that folder on the site.

Thoughts on this?

**Comment by DanVanAtta** [comment]
General agreement.
I've migrated `docs/` to `help/` and have been importing the legacy documentation there. We'll need a few more passes of cleanup and organization. We're getting a bit closer to having consolidated documentation.
