### ISSUE TITLE
Map Detail Pages

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#11]
I just noticed, on some maps I would really want to look at the detail and analyze what for example the eastern europe situation would look like.

Seems like we should have a feature that if you click a map thumbnail, it shows a larger image (first version can be a link to a larger image version, but could be some nice jquery or html4 options too)

**Comment by williamdekryger** [comment]
True, maybe we should write a script that reads the XML to find starting unit positions and territory owners and compiles a starting scenario PNG...Totally random idea...Anyways, it would be relatively simple to have a darkbox with the map image zoomed at 100%, I don't know, just brainstorming. Other ideas?

**Comment by DanVanAtta** [comment]
@williamdekryger , we've basically figured out we'll likely have the map images be links to 'map detail pages' right, instead of just larger image zooms?

**Comment by williamdekryger** [comment]
I am merging this thread with #33, to cover more ground.
