### ISSUE TITLE
Page URL Naming Conventions

### ISSUE THREAD

**Issue by williamdekryger** [triplea-game/triplea-game.github.io#110]
Several of the pages on the site now have two-word names, including, "bug_report," "upgrade_notes," and "release_notes." These pages all use an underscore ("_") to separate the two words. These URLs are potentially subject to change anyways (see #109), so I'd like to take the opportunity to decide whether we standardize around the underscore, or use either dashes or no space, which become, "bug-report," "upgrade-notes," and "release-notes," and "bugreport," "upgradenotes," and "releasenotes," respectively.

My personal preference is the dashes, but I'm open to anything, even the status quo, but I'd like a convention for future changes. The final decision will be placed in the README as well as other conventions down the road.

**Comment by DanVanAtta** [comment]
Let's do underscores please, it's typical of file names and URLs, and reads more easily than dashes
