### ISSUE TITLE
mobile friendly

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#12]
Has anyone tested it? How are we?

"the site should be mobile friendly..." Veqryn Aug 30, 2015; 4:50pm

From: http://tripleadev.1671093.n2.nabble.com/TripleA-Website-Redesign-Migration-to-Github-Pages-tp7589306.html

**Comment by williamdekryger** [comment]
Mobile support is definitely on the docket. It is a simple matter of a few CSS lines to force the columns in the footer, and on the contribute and community pages to line up under each other on smaller screens.

**Comment by Silvergrail** [comment]
Do you mind if I give the mobile optimization a go, if the issues is still present of course? I'm new to Github but I've quite a bit of HTML5 and CSS especially with mobile friendliness as a priority :)

**Comment by williamdekryger** [comment]
Yes, we are glad for any help. Try to keep code as small as possible, and keep stuff mainly CSS based, as you did on the menu. There are columns across the site on a few different pages (as well as in the footer) which need fixing in the same way as the menu. Other than that, does anyone see any other problems?

**Comment by DanVanAtta** [comment]
#22 and #21 are some more mobile bugs. It appears there is quite a bit of work to be done. Really appreciate the help. Please feel free to create new issues to track any problems you see, even if you don't plan on fixing them personally.
