### ISSUE TITLE
 ”Contribute Maps Documentation Community” thicker text

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#13]
" top ”Contribute Maps Documentation Community” should be thiker text if posible."

Frostion
Oct 08, 2015; 5:53am
http://tripleadev.1671093.n2.nabble.com/TripleA-Website-Redesign-Migration-to-Github-Pages-tp7589306p7589868.html

**Comment by williamdekryger** [comment]
I thickened and softened the text in a9b47001d19e9fae49a105b866edbc113c09b032. Please give your feedback.

**Comment by DanVanAtta** [comment]
Looks good to me
