### ISSUE TITLE
more contast in metal bar and light grey text

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#14]
The buttom metal bar and light grey text should have more contrast. Maybe try out a darker metal background? 

Frostion Reply
Oct 08, 2015; 5:53am

http://tripleadev.1671093.n2.nabble.com/TripleA-Website-Redesign-Migration-to-Github-Pages-tp7589306p7589868.html

**Comment by williamdekryger** [comment]
I increased the contrast in b62fae95cd01a05e5f9d06cee43ca1b201e5fec4. Is that better?

**Comment by DanVanAtta** [comment]
Let's cut a new issue if any additional changes are needed
https://github.com/triplea-game/triplea-game.github.io/issues/new
