### ISSUE TITLE
https

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#167]
https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by RoiEXLab** [comment]
Oh right... I always forget you aren't an owner of the triplea-game org, just a contributor with write access... Thanks for adressing this issue though!

**Comment by RoiEXLab** [comment]
@ron-murhammer just mentioning you to remind you of this...

**Comment by ron-murhammer** [comment]
@DanVanAtta @RoiEXLab "Enforce HTTPS — Unavailable for your site because you have a custom domain configured (www.triplea-game.org) 
HTTPS provides a layer of encryption that prevents others from snooping on or tampering with traffic to your site.
When HTTPS is enforced, your site will only be served over HTTPS."

**Comment by RoiEXLab** [comment]
From github support:

> Hey there,
> 
> HTTPS support is something the team would love to add, though as you've noticed it is currently not available. We are waiting on our CDN provider to be able to provide support for this.
> 
> One alternative that some of our customers have had success with is CloudFlare:
> 
> https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/
> 
> We don't provide support for it though, so you would need to contact them with any difficulties you have.
> 
> I've added a +1 to this suggestion on our internal Feature Request List.
> 
> Best,
> Shawna

**Comment by kskarthik** [comment]
Better use a CDN like cloudflare or max CDN

**Comment by DanVanAtta** [comment]
Closing for the moment. Mostly because the benefit for `https` for the website is not very compelling. The website is all static content. If there is a use-case to integrate with the forum better or something else, we can very well revisit this topic. In the meantime, I'm quite positive we should focus our efforts elsewhere where it will be more impactful.

**Comment by RoiEXLab** [comment]
HTTPS seems to be available now for custom domains, `https://triplea-game.org` is a valid URL now.
Now the question is if we should enforce it, I'd strongly vote for it!

**Comment by ssoloff** [comment]
Yeah, if you've been following isaacs/github#156, you'll note they seem to have been rolling it out slowly for the past few weeks, but I don't think GitHub has made any official announcement yet.  We should probably wait until that happens before we commit to it just in case there's some hidden string attached.

**Comment by DanVanAtta** [comment]
my 2 cents, let's wait. Https for website does not present very much benefit.

**Comment by RoiEXLab** [comment]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

It's official!
I don't think we need any further configuration. I changed the DNS to a simple CNAME record (instead of A) a couple of months ago.

@DanVanAtta Enforcing HTTPs should (at least in my understanding) redirect any HTTP traffic to HTTPs.

**Comment by RoiEXLab** [comment]
@DanVanAtta @ron-murhammer @ssoloff If there aren't any objections, I'll just enforce HTTPs on friday to enhance the SEO even further

**Comment by DanVanAtta** [comment]
No objections here. I think you are clear to proceed at a time convenient to you @RoiEXLab.

**Comment by RoiEXLab** [comment]
I just checked the checkbox to enforce https, I'm still having some trouble to migrate the google search console tools to https, but I'll probably just modify some of the google html files if the DNS method doesn't work
