### ISSUE TITLE
Optimize website for mobile

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea-game.github.io#170]
Just leaving this here to remind us of this task...

**Comment by DanVanAtta** [comment]
Generic tracking tickets are not good things. We'll get into a habit of leaving lots of stuff laying. Tickets should ideally be actionable, so you can spend 2-3 minutes reading a ticket and then have/know what to do.

@RoiEXLab  is there anything in specific you were looking to do for mobile?

**Comment by RoiEXLab** [comment]
I was mainly thinking of the navigation... 
Currently the Navigation on mobile takea about 70% of the page height, I will turn this into a dropdown menu sometime (for mobile)
Also the title is not quite fitting on a portrait oriented screen (I don't know what it's actually called)
