### ISSUE TITLE
Back button unexpected behavior

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#193]
@RoiEXLab  FYI: part of  #192 may need to be backed out / redone a bit. The problem I see,  for example when, going via these pages:

- http://www.triplea-game.org
- http://www.triplea-game.org/help/
- http://www.triplea-game.org/dev_docs/
- http://www.triplea-game.org/release_model

The back button takes me to:
- http://www.triplea-game.org

Instead of:
- http://www.triplea-game.org/dev_docs/

To immediately fix this/close we have some options (not limited to):
- disable the javascript, ie: back it out/remove it. Then fix the deeper issues with further iterations.
- update the button to always go to 'dev_docs' instead of home page, maybe call it 'docs home' or 'back to index' instead of 'back' . 

I think we have these two deeper problems to solve in the dev docs:
1. most immediately, organization, just navigation the pages is not easy, can't click around to get everywhere
2. too much of it given how it is organized. Pruning down the docs and better organization would help.

Navigation is pretty tied to organization,ultimately the two deeper problems represent the goals we wish to accomplish.

**Comment by RoiEXLab** [comment]
@DanVanAtta  The back button is only a thing for pages with the "longpage" layout, which is supposed to be used for documentation...
So we shouldn't have any problems \:-)

**Comment by RoiEXLab** [comment]
I opened #195 in order to adress part of this issue...
Currently every page has a "root" defined, so technically it's not a back button, but a parent directory button instead...
What we could do is navigate through the browser history using javascript. `history.back();` is equivalent to pressing the back button in your browser...

**Comment by RoiEXLab** [comment]
@DanVanAtta But I agree that the structure of the docs is currently pretty bad...
