### ISSUE TITLE
Game Manual Available from Website

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#20]
Feature: Game manual available from the website

**Comment by williamdekryger** [comment]
@DanVanAtta The manual is already on the website:

![game manual](https://cloud.githubusercontent.com/assets/5250014/13223586/ca210392-d97c-11e5-9bfa-bd8faad3b91c.png)

However, I will definitely be revamping the docs as I have time, so keep that in mind.
