### ISSUE TITLE
Mobile: CSS changes need to fix scrunched links and overlap

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#22]
Footer needs some CSS work it looks like for mobile.

**Comment by Shumaan** [comment]
Any ideas on how to scrunch all the links better on mobile? I mean the simple solution is to simply make each link on its own line in the footer on mobile. However, that seems like it would make the page unnecessarily massive, with a major part of that just being the footer.

**Comment by DanVanAtta** [comment]
IMO not all the links need to be there. If we could put two per row, that would save a good bit of space. @williamdekryger , any additional ideas maybe?

**Comment by williamdekryger** [comment]
@Shumaan @DanVanAtta I was planning on doing one link per line with the exception of those that could be converted to icons. Any objections?

**Comment by DanVanAtta** [comment]
seems good to me. There may be some links that we can prune out in case the list gets really long.

**Comment by williamdekryger** [comment]
@Shumaan @DanVanAtta Pull request #34 addresses this issue. Please take a look at that and tell me what you think.
