### ISSUE TITLE
http://www.triplea-game.org/screenshots/ Gives 404

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea-game.github.io#221]
http://www.triplea-game.org/screenshots/ Gives 404

The screenshot menu option gives a 404 error

**Comment by ssoloff** [comment]
That page is missing a `permalink` property.  Not sure if that's the problem.  Let me spin up a Jekyll container and see if I can reproduce it locally.

**Comment by ron-murhammer** [comment]
Cool. Ping me if you submit a fix.

**Comment by ssoloff** [comment]
@ron-murhammer Sorry, the permalink was a red herring (it's never had one to begin with).  I'm running `master` locally and the screenshots page comes up fine.  There may be something wrong in production.

**Comment by ron-murhammer** [comment]
Hmm. I'm still wondering if permalink isn't needed in production. Might be worth trying.

**Comment by ron-murhammer** [comment]
@ssoloff Looks like that fixed it :). Nice work. Closing this.

**Comment by ssoloff** [comment]
@RoiEXLab Can you explain why the absence of `permalink` fails in production but works fine when I run Jekyll locally?  Is there some configuration in production that's not captured in the repo?

**Comment by RoiEXLab** [comment]
@ssoloff I have no idea!
I'm assuming github pages uses a slightly modified version of jekyll?

**Comment by ssoloff** [comment]
@RoiEXLab Or maybe it's the Docker image I'm using that has the "extra juice" that allows it to work without a permalink?
