### ISSUE TITLE
Most dev docs links are broken

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea-game.github.io#224]
I'm getting a 404 on **all** the internal links from the [root dev docs page](http://www.triplea-game.org/dev_docs/dev/) **except** for the following:

* http://www.triplea-game.org/dev_docs/dev/code_standards/
* http://www.triplea-game.org/dev_docs/dev/builder_bot/

It looks like the problem is that the links include a trailing slash but the permalinks on the pages themselves do not include the trailing slash.

@RoiEXLab

**Comment by RoiEXLab** [comment]
@ssoloff Could you open a PR on this one?

**Comment by RoiEXLab** [comment]
I'd prefer changing the permalinks instead of the hrefs

**Comment by ssoloff** [comment]
@RoiEXLab Does the link checker not validate internal links?  I would have thought this issue would be caught during a build.

**Comment by RoiEXLab** [comment]
#225 has been merged, closing!
