### ISSUE TITLE
download_html_validator intermittently fails on Travis PR builds

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea-game.github.io#236]
The `.travis/download_html_validator` script uses the GitHub API to download the latest release of the `validator/validator` project.  This requires authenticating via an OAuth token, which is stored in the encrypted environment variable `AUTH_TOKEN`.  However, for security reasons, encrypted environment variables are not visible to PR builds.  Thus, PR builds will attempt to connect to the GitHub API without authenticating.  This subjects PR builds to rate limiting against the source IP, which presumably means we're competing with every other Travis project making unauthenticated requests to the GitHub API at that time due to NAT.  For example, the [Travis build](https://travis-ci.org/triplea-game/triplea-game.github.io/builds/266051128) for #235 failed for this reason.

We probably need to figure out an alternative mechanism for downloading the latest `validator` release that does not use the GitHub API in order to avoid intermittent failures of PR builds.  For example, we can simply lock down the version of `validator` we're using and upgrade to newer releases as needed.  Always depending on the latest version can lead to other problems, such as breaking CLI changes after a major version bump.

@DanVanAtta @RoiEXLab @ron-murhammer

**Comment by RoiEXLab** [comment]
Good points, we should probably just use a fixed version then.
Feel free to create a PR to adress this issue if you have the time, I won't be able to do that until Friday
