### ISSUE TITLE
Developmet Documentation (dev_docs) gives 404 - File not found

### ISSUE THREAD

**Issue by jelinekb** [triplea-game/triplea-game.github.io#249]
Readme (triplea-game/triplea) indicates that development documents are located at http://www.triplea-game.org/dev_docs/

Clicking link, however, results in 404 - File not found

**Comment by ssoloff** [comment]
Thanks for reporting, @jelinekb.  We forgot to update this link when we moved the dev docs from the website to the dev repo.  triplea-game/triplea#2287 fixes this and is now live.
