### ISSUE TITLE
Buttom menu text underline

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea-game.github.io#25]
Regarding the website:
The buttom menu text turning red when “mouseover” is great. But have you tried to remove the underlines? The underline looks and seems unnecessary to me. Every one looking at the bottom of the page must know that it is full of links, especially if the person is mouseovering and the tekst turns red.

**Comment by williamdekryger** [comment]
This is quite plausible. Any other people want to give an opinion?

**Comment by Shumaan** [comment]
I know I'm a little late, but I'm all for removing the underline.

**Comment by williamdekryger** [comment]
@FrostionAAA @Shumaan The underline has been removed as of 3dda2156a1fc39949f2bf1387782359ea745666b.
