### ISSUE TITLE
Link length

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea-game.github.io#26]
Regarding the website:
If you want to keep the bottom links uniform and as short as possible, you could rephrase ”Introduction to TripleA” to ” TripleA Introduction” and “Playing by Email and by Forum” to “Playing by Email and Forum” / “Playing by Email or Forum” (whatever is more correct). Especially the latter current link/phrase sticks out by being a bit long compared to the other links.

**Comment by DanVanAtta** [comment]
Footer needs a number of updates IMO. I opened #27 to track changing the links themselves, I think the categories could be switched up and improved. Like for example expanding on the docs and have a "how to play" , "faq", "hosting a game" all spelled out in the footer would good.
