### ISSUE TITLE
Footer updates

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#27]
Ticket to discuss/track how to change the footer. In specific I think the links need re-organization. 

For example the videos should likely be a section on a docs page, and a single link in the footer rather than a whole column.

Another example, expanding on the docs and have a "how to play" , "faq", "hosting a game" all spelled out in the footer would good.

Related to #26, while considering new links make sure that the columns line up nicely

**Comment by DanVanAtta** [comment]
@williamdekryger I'm thinking of doing a first draft of this soon. Let me know if you get a chance to start work on this.

**Comment by Shumaan** [comment]
Hey, new around here, but I thought I would start hashing through some of the critical things...which seemed like this. I'm still trying to find my way around and get myself caught up on anything. Is this valid for me to make a draft of?

**Comment by DanVanAtta** [comment]
@Shumaan , feel free, the help is appreciated. The few outstanding items I had/have are in the open PRs.

**Comment by williamdekryger** [comment]
@DanVanAtta I believe that this has been resolved, right? May I close #26 as well?

**Comment by DanVanAtta** [comment]
@williamdekryger  - yes
