### ISSUE TITLE
Website CNAME Changes

### ISSUE THREAD

**Issue by williamdekryger** [triplea-game/triplea-game.github.io#28]
Hello All,
Just wanted to note that the website is down due to the fact that the CNAME file has been changed to point to http://triplea-game.org, which does not exist. Is is easy enough to just reverse the commit. Is everyone in agreement, or is there something I don't know?

**Comment by DanVanAtta** [comment]
Deleted. DNS A-record not working apparently.

**Comment by DanVanAtta** [comment]
PS - We also  own triplea-game.org as well for the next 10 years.

**Comment by DanVanAtta** [comment]
reverted, #29 open for DNS config
