### ISSUE TITLE
DNS config for www.triplea-game.org

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#29]
We own triplea-game.org for the next 10 years. Does anyone have any guesses on what the correct DNS configuration would be so www.triplea-game.org would be served by triplea-game.github.io?

**Comment by williamdekryger** [comment]
@DanVanAtta We should try to get this set up. I see that you registered with Namecheap. Here is the [Github support doc](https://help.github.com/articles/setting-up-an-apex-domain/) and the [Namecheap support doc](https://www.namecheap.com/support/knowledgebase/article.aspx/544/51/how-do-i-set-up-host-records-for-a-domain-when-i-use-freedns) to help you with what you need to do. The most important thing is to put these two IP addresses as nameservers:

* 192.30.252.153
* 192.30.252.154

I can walk you through it if you catch me on Gitter. Feel free to ask me any questions you have.

**Comment by DanVanAtta** [comment]
DNS records added:

![dns_records](https://cloud.githubusercontent.com/assets/12397753/13314514/7489c506-db5a-11e5-90a4-ef53eb4f56ec.png)

**Comment by DanVanAtta** [comment]
to update this.. the change was reverted for the DNS.. It did not work :-1: 

@williamdekryger , feel free to experiment around if you think you can get it working. You should have access/credentials to the DNS

**Comment by williamdekryger** [comment]
@DanVanAtta Hmm...Perhaps we should contact support. Surely we're not the only one of their customers trying to send a domain to Github Pages.

**Comment by williamdekryger** [comment]
@DanVanAtta I'm going to need a resend of that invitation. It seems to have expired. Have you tried contacting support yet?

**Comment by DanVanAtta** [comment]
This is done! Thanks @williamdekryger  for getting it set up, I didn't realize how nice it would be to have a proper domain name :+1:
