### ISSUE TITLE
Forum (Website) elements are hard to identify

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea-game.github.io#295]
There must have been some changes recently leading to some elements of the forum (website) being hard to identify (Chrome and Opera):

![traws](https://user-images.githubusercontent.com/20812775/35798979-a1e77260-0a64-11e8-88b6-660e3aae473f.PNG)

Also the text sometime is really small and hard to read:

![traws2](https://user-images.githubusercontent.com/20812775/35799406-dd06680a-0a65-11e8-8faf-79a6f5a8dda7.PNG)

Things become unreadable here (size and colors):

![traws3](https://user-images.githubusercontent.com/20812775/35799615-95d59202-0a66-11e8-9313-0e669437b004.PNG)

Writing text is writing white on white:

![traws4](https://user-images.githubusercontent.com/20812775/35799819-4bd20680-0a67-11e8-8c7e-43d9bdc4bd06.PNG)

And my written text appears as (maybe) fontsize 3:

![traws5](https://user-images.githubusercontent.com/20812775/35799993-dbf33fae-0a67-11e8-99a7-e41eec484352.PNG)

I am not going to screenshot everything here, but all in all fontsize, colors and menus appear to be close to unusable.

**Comment by prastle** [comment]
Edge and Firefox seem to be working fine.  Just for info.

**Comment by RoiEXLab** [comment]
Ahhh.
I know what's going on...
See https://github.com/NodeBB/NodeBB/issues/6306
Just set your skin back to the default one to temporarily work around this issue.
So it's not our fault

**Comment by panther2** [comment]
Thank you so far.

**Comment by RoiEXLab** [comment]
@panther2 NodeBB just released a patch.
This patch has been applied, and everything should be working fine again.

**Comment by panther2** [comment]
Indeed, confirmed! Thanks.
