### ISSUE TITLE
Developer Documentation Page

### ISSUE THREAD

**Issue by williamdekryger** [triplea-game/triplea-game.github.io#3]
We recently removed the "Developers" page (e9697e1a95d0909359bb66d0c69d4341529cafaf). What was the intended replacement? Where should I send people who want to contribute, or even just run source? Do we need to write a new "Developers" page? @DanVanAtta specifically, since you wanted it removed...

**Comment by DanVanAtta** [comment]
The how to contribute page IMO captures the intent of the developer section for the most part. That in combination with the README and wiki of the github site - and I think we should be covered.

The github site has and needs developer steps and documentation. So I'd like to avoid duplication of those links and materials between the website and github site. It would also be quite painful and not very appropriate to have to update the website code whenever the developer documentation is updated, or can be improved. It's also very natural to have those steps be in wiki so everyone can continually improve the text and accuracy of the instructions. On a website, and the content will be very static. We do not want the developer documentation to be "very static."

So my preference for now is to have the website more aimed at just getting new developers over to the github site. The github site is the first place developers need to go anyways, and today it is hosting the setup and process documentation anyways that developers would be looking for.

Last, the primary goal of the website it to serve new players, to get them to download the game and to learn to play. IMO let's focus on that for the website for a good while. Thus, the section in the 'how to contribute' pointing developers to the repository I think is sufficient for now.

**Comment by williamdekryger** [comment]
Got it. So we're linking to the Github wiki, then? If so, I should put a footer link...What wiki pages do you have in mind to link to for new devs?

**Comment by DanVanAtta** [comment]
Link to the main page please.
I'd like for the github readme to have the wiki links and the next steps. We do have some work to do on the GitHub side to get the documentation cleaned up, organized and linked.

**Comment by DanVanAtta** [comment]
So seems like we'll be using the how-to contribute page to send people directly to the triplea-game/triplea github website. Please re-open if any other action items are still outstanding.
