### ISSUE TITLE
Remove google tracking

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#323]
I don't think we're actively using any of google's SEO tools. Let's work to remove google analytics and google tracking. I'd be curious if we are getting benefit from the tracking/analytics, otherwise this is a discussion and tracking ticket for the removal.

**Comment by RoiEXLab** [comment]
I'm fine with removing Google analytics, we might want to keep the country data around in case we ever want to check if we want to target a specific region for bot servers or something in the future

**Comment by DanVanAtta** [comment]
Cool, I noticed the google file and always my adblocker catching trackers on the forums and website. I thought it was kinda odd, TBH I don't think I even have the analytics login anymore.

@RoiEXLab is this something you can add to your backlog?

**Comment by RoiEXLab** [comment]
Note that AFAIK Google search console isn't affected by this at all.
It just tracks how many people actually klick on the Google search results and was super helpful when merging old forum and website to get the high seo rank

**Comment by RoiEXLab** [comment]
I should be able to do that during the weekend 👍
I'll see if there's some sort of export feature and keep the data we have so far, and disable any future tracking afterwards.
Even if this affects seo in some shady way, we should be at a point where our seo is high enough

**Comment by RoiEXLab** [comment]
@DanVanAtta Just noticed that we actually don't use google analytics at all for triplea-game.org, just the SEO monitoring, my ad-blocker doesn't show any blocked trackers either except for the facebook link in the lower right corner.

Also I'm pretty sure we don't need the verification file anymore, the DNS entry has a proper verification token. If you give me your Gmail, I can add you to the list of owners of the Google Search Console

We do use google analytics for the forum though, should we remove it there then?

**Comment by RoiEXLab** [comment]
And I can export all the information to a google spreadsheet document which is nice, so I can share it with y'all

**Comment by RoiEXLab** [comment]
Checking the actual tracked information, it's actually not that much.
Noteworthy:
Geographics details
Page visit flow, i.e. tells which pages are browsed first when opening the forum

**Comment by DanVanAtta** [comment]
Ah, thanks for that background. Sounds like we can remove all the google stuff?

**Comment by RoiEXLab** [comment]
In this repository? Yes!

**Comment by DanVanAtta** [comment]
forums too? That was where my ad-blocker was complaining. Is the info really valuable there? 
I certainly had an opinion shift over the last few months and supporting google's ad business on TripleA's back seems wrong unless it's really useful to us.

**Comment by RoiEXLab** [comment]
Yes, but there it's more or less just a configuration thing, no custom code.

I'll export all the existing information to a spreadsheet and we can then decide what's actually useful, and delete the rest

**Comment by RoiEXLab** [comment]
But not today, I'll do that tomorrow, it's getting late

**Comment by DanVanAtta** [comment]
No  rush, sounds good and thank you!

**Comment by RoiEXLab** [comment]
@DanVanAtta Removed google analytics, and exported all the data I could get my hands on to google spreadsheets. Of course the analytics site has a better way to represent the data, and probably knows a lot more than it really shows, so the data isn't really much.

I believe there are only really 3 relevant datasets:
User languages
User country
User platform (amount of mobile users, mac users, etc.)

**Comment by RoiEXLab** [comment]
I haven't actually merged the data into a single document, thus why I shared so many documents with you.

I mean if @prastle or some mod feels like they can analyse the data and present the results in some meaningful way, they can have all of the spreadsheets.
This is also another screenshot I made because this couldn't be exported:
![Data flow](https://user-images.githubusercontent.com/8350879/64065895-cac71380-cc13-11e9-8909-057e0164031f.png)

Note that all the spreadsheets are labeled in german (because my google is set to german), so you'll have to replace the decimal `,` with a decimal `.` and maybe put all the titles in google translate or something. Most of them should be pretty straightforward

**Comment by RoiEXLab** [comment]
I opened #324 to remove the google seo file, which is no longer used.
But apart from that this ticket should be done

**Comment by prastle** [comment]
@RoiExLab 
Giggles Ya its "German to me "  Explain what you need me to look at or up load it to google drive in English and and pm me the link on the forum.

**Comment by RoiEXLab** [comment]
@prastle If you PM me your gmail over the forum or something I can add you to the list of editors of the spreadsheet, it's the easiest way to share the documents, there are like 20 with like 5 rows 10 columns each

**Comment by prastle** [comment]
PMing
