### ISSUE TITLE
Install jekyll-seo-tag plugin

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea-game.github.io#339]
This looks like an interesting extension. What do people think?

A Jekyll plugin to add metadata tags for search engines and social networks to better index and display your site's content.
https://github.com/jekyll/jekyll-seo-tag

I could make the necessary modifications in my branch as a PR, and add any additional configuration changes as a subsequent PR.

**Comment by RoiEXLab** [comment]
I mean our seo score seems to be pretty decent, but we could give it a shot

**Comment by DanVanAtta** [comment]
It might be worth letting reviewers test any gem dependency in case we run into any kind of Ruby dependency problems (*cough* hell).  With that said, boosting SEO is very valuable, I'm quite in favor.

**Comment by DanVanAtta** [comment]
@tvleavitt , I took a stab at this with this branch: https://github.com/triplea-game/triplea-game.github.io/tree/jekyll-seo-tag
I was not able to see any differences in the meta tags. I'm curious if you'd like to pick this task up or could give any pointers.

**Comment by tvleavitt** [comment]
I'll see if I can find the cycles to look at this over the next few days.

**Comment by DanVanAtta** [comment]
Managed to knock this out: https://github.com/triplea-game/triplea-game.github.io/pull/400

Thank you @tvleavitt for the pointer to the cool tool!
