### ISSUE TITLE
Sitemap out of date

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea-game.github.io#341]
The contents of sitemap.txt do not reflect the web site's current structure, and in fact point to non-existent pages:

http://triplea-game.github.io/
http://triplea-game.github.io/about/
http://triplea-game.github.io/contribute/
http://triplea-game.github.io/maps/
http://triplea-game.github.io/community/

I think the contents should be...

http://triplea-game.github.io/
http://triplea-game.github.io/download/
https://triplea-game.github.io/old_downloads/
http://triplea-game.github.io/maps/
http://triplea-game.github.io/maps-list/maps/
http://triplea-game.github.io/maps-list/mods/
http://triplea-game.github.io/release_notes/
http://triplea-game.github.io/user-guide/

Question: should this actually be "triplea-game.org" instead as the domain? Let me know. Also, this should really be dynamically generated.

**Note:** this will have had limited impact, as per [sitemaps.org](https://www.sitemaps.org/protocol.html#informing), without a robots.txt file informing search engines of its location, it won't be used unless we manually submit it (doubt that's happening, maybe should be part of the release process?). Filing a separate issue request about the lack of a robots.txt file.

**Comment by DanVanAtta** [comment]
Sitemap is now autogenerated with a jekyll-plugin!   :smile:
