### ISSUE TITLE
Create xml version of sitemap.txt

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea-game.github.io#343]
We may wish to consider generating our sitemap automatically, and using the XML format specified below to ensure maximum SEO effectiveness:

https://www.sitemaps.org/protocol.html

**Comment by DanVanAtta** [comment]
Excellent suggestion - it was not too bad to wire up a jekyll plugin.

The sitemap is looking good now, even indexes all of the map pages: https://triplea-game.org/sitemap.xml
