### ISSUE TITLE
Link rel meta tag in site html refers to http://localhost:4000/

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea-game.github.io#348]
The following meta tag is embedded in the site content:
<link rel="canonical" href="http://localhost:4000/">

Based on the information below, I believe this is invalid:

The Canonical meta tag is actually a link element. By adding it you define which URL is the original URL of a page. If you have a page with both a mobile and a desktop version, Google sees these as duplicate versions of the same page. 

If the same information is available on multiple URLs, then there is duplicate content. The best solution is to prevent duplicate content from occurring. But in other cases, the canonical tag is the best way to resolve duplicate content.

https://www.metatags.org/all-meta-tags-overview/the-unknown-metatags/canonical-tag/

**Comment by RoiEXLab** [comment]
@DanVanAtta well the tag is defined here:
https://github.com/triplea-game/triplea-game.github.io/blob/69e6873a79c8a9604c72c59a9776fa5422fe4cde/_includes/head.html#L10

Because Jekyll listens on localhost:4000 by default that's the value that is inserted there

**Comment by DanVanAtta** [comment]
We could just remove it?

**Comment by RoiEXLab** [comment]
Well it's meta information, so yes.
I assume it was originally inserted by some template or in order to improve SEO, not sure if it helps with the latter

**Comment by DanVanAtta** [comment]
It looks like the canonical link is fixed now on the website:

The rendered HTML source has:
![image](https://github.com/triplea-game/triplea-game.github.io/assets/12397753/b90aa534-3700-42a2-8928-6d48cfd69b18)

I don't know when this was fixed, it looks like the same 'meta' line is in the source code as it has been.

@tvleavitt  please give a holler if you see it differently somewhere else
