### ISSUE TITLE
Release notes table does not have borders

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#350]
Release notes table is not as easy to read as it could be. Needs borders: https://triplea-game.org/release_notes/

**Comment by RoiEXLab** [comment]
@DanVanAtta IIRC I pasted some CSS somewhere around the "fix connectivity check" PRs that might be able to fix this problem.
There were 2 variants, one requiring to use html directly

**Comment by DanVanAtta** [comment]
This has been done
