### ISSUE TITLE
Outdated Release Status (2020/12/24)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea-game.github.io#364]
In the 
https://triplea-game.org/map/over-the-top/
maps page, I can see:
>(Requires pre-release 1.9.0.0.6322 or higher)

I believe it is a long time since 1.9.0.0.6322 hasn't been a pre-release if it ever was a release.

I believe this is a general problem.

**Comment by DanVanAtta** [comment]
This is fixed by: https://github.com/triplea-game/triplea-game.github.io/pull/365
