### ISSUE TITLE
Facebook Like and Share buttons

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea-game.github.io#37]
Like and share button for the githubsite:

1. Include the JavaScript SDK on your page once, ideally right after the opening <body> tag. 

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

2. Place the code for your plugin wherever you want the plugin to appear on your page.

<div class="fb-like" data-href="http://triplea-game.github.io/" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>

**Comment by ZjelcoP** [comment]
ehhh, I'm sure there was code in there.... You took it???

**Comment by ZjelcoP** [comment]
Ah yes, code seems generic, you can find it anywhere.

I'd say top right corner is a nice spot.
Must say the footers are a bit hidden, have to scroll for them. No space to get them up a bit higher?

**Comment by ZjelcoP** [comment]
This is for a button for the facebook page:
1. Include the JavaScript SDK on your page once, ideally right after the opening <body> tag. 

`<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>`

2. Place the code for your plugin wherever you want the plugin to appear on your page.

`<div class="fb-page" data-href="https://www.facebook.com/TripleAwargame/" data-tabs="timeline" data-width="300" data-height="70" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/TripleAwargame/"><a `href="https://www.facebook.com/TripleAwargame/">TripleA</a></blockquote></div></div>`

Origin and extra settings:

[https://developers.facebook.com/docs/plugins/page-plugin/](url)

**Comment by DanVanAtta** [comment]
@williamdekryger , can i volunteer you for this?

**Comment by williamdekryger** [comment]
@DanVanAtta Yeah, it shouldn't be too time-consuming. Just as a note, I will be pushing the DL page today and starting a pull request.

**Comment by ZjelcoP** [comment]
@DanVanAtta : I believe you have access to the sourceforge page (Warclub as well??).
Would you please create the link to the facebookpage there?
I'll ask Dave Jensen to do the same.

Cheers

**Comment by RoiEXLab** [comment]
@DanVanAtta this can be closed
