### ISSUE TITLE
Increase readability of list items in footer.

### ISSUE THREAD

**Issue by NathanNOSudo** [triplea-game/triplea-game.github.io#379]
I have a suggestion to improve the site's readability. Currently the list items in the footer are pretty compacted on top of each other, adding padding or margin will increase the footer height but adding 1.3 to 1.5 em line-height to your main.css for ul > li tags substantially increase the clarity of each item as well as readability. I have Included a before screenshot and an after screenshot. If the team is ok with it, I would gladly make the change and submit a PR. Additionally I do have some down time and am willing to help with any other improvements / fixes to your site!

Current footer: 
![old-line-height](https://user-images.githubusercontent.com/49554888/196012933-1c23d8fd-fc41-46dc-8c3b-37e2f108841e.png)

Suggested changes: 
![suggested-change](https://user-images.githubusercontent.com/49554888/196012939-f1400a39-eeee-4870-813c-db03eab85f61.png)

**Comment by RoiEXLab** [comment]
@NathanNOSudo Seems like a good suggestion. Feel free to open a PR 👍🏼

**Comment by DanVanAtta** [comment]
Agree, that helps legibility.

We should consider as well (as a follow-up) whether we want all of the video links. Some of them are pretty out of date and perhaps not even worth linking at this point.

**Comment by NathanNOSudo** [comment]
Will do! Sorry for the delay, I have been on vacation.

**Comment by DanVanAtta** [comment]
Was working on the footer, took a quick stab at this in #398
