### ISSUE TITLE
Add List of Strategy Wargame Mechanics for Map makers

### ISSUE THREAD

**Issue by williamdekryger** [triplea-game/triplea-game.github.io#38]
I gleaned this question out of the forums the other day:

> Has anyone compiled a master list of board wargame "mechanics" that you can and can't simulate with TripleA? For instance, there are known solutions for terrain and weather, but none that I know of for fog of war or border limits (how many units can attack across each border). It would be really useful to have a master list where people share ideas.

Perhaps we should consider this as an addition to our already planned documentation. We would have to update it, though, as map-makers found more and more intriguing methods to implement, say railroads, or ranged units, or any map feature that the engine can be twisted to support.

Any thoughts on this?

**Comment by DanVanAtta** [comment]
Download page first!  We've already a lot of overhead and a lot of things to do. If you want to take this on and can knock it out, I'm not going to stop you.

**Comment by DanVanAtta** [comment]
A wiki might be better since there would be a lot of content to manage, making it self-managed might be very good. Otherwise this seems like it would be a valuable page for the map makers, an XML recipe book effectively.

**Comment by williamdekryger** [comment]
Alright, I'm closing this for the time being, as I have other priorities, and won't be able to spearhead this. I may be willing to try with a collaborator, but for now, I don't see this getting done any time soon.

To sum up, the original idea was to have a set of documents that explained in greater detail the different parts of Pact of Steel 2 XML, basically documenting all of the different features of the XML, and a list of wargame "mechanics" that have been achieved using TripleA, and how to implement them.
