### ISSUE TITLE
Menu Bar links only work from the homepage

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#4]
From  http://triplea-game.github.io/

Click any of the menu bar links, like 'community' for example, the new URL is:
http://triplea-game.github.io/community/

Now click the same link again, or any of the menu bar links, and you get a 404. The URL is now:
http://triplea-game.github.io/community/community

**Comment by williamdekryger** [comment]
Ah. Thanks for the heads-up. I had to change a bunch of permalink stuff to get the site ready for pruduction. I will look into this. It is an issue on each page, to be precise, and it breaks images on the subpages as well. Should be a missing trailing slash somewhere...

**Comment by williamdekryger** [comment]
Fixed in 202b9e05155075eb88bcf0b6412b57c0c4b3ab78.
