### ISSUE TITLE
Entertainment during download

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea-game.github.io#41]
From our discussion on sourceforge:

> Reading game -info or the rules when downloading? ....text. General game-info could be nice if kept short and to the point. Perhaps a slideshow/visual presentation of TripleA's finest will grab people's attention and show them what is there for them to discover. 

Think the slideshow would be really nice. Can show off some great maps and already give some game information like: 
100 maps ready for download!
Play online in the lobby!
Combined with visually nice pics.

I can put it together, meaning the slides.

Implementing it on the site (not my skill):
1: will it not slow down downloading too much?
2: plenty time to show it, my download takes some 3 mins with good internet i believe
3  should start after download has begun
4  Slideshow could be used elsewhere as promotional material as well 
(already thinking bigger, but this could be a start) [http://tripleadev.1671093.n2.nabble.com/A-video-request-tp6219491p7591662.html](url)

**Comment by DanVanAtta** [comment]
Linking to the rule book, or previewing it was my previous thought. 

A slideshow I like since it's light. Instructions  / tips about game play would potentially be nice. Or we could also have some change notes located there. 

IMO up to @williamdekryger  depending on what he can support / the direction he wants to go with the download UX

**Comment by williamdekryger** [comment]
@ZjelcoP @DanVanAtta I was in the midst of converting the rulebook to Markdown for website purposes. However, we potentially could still use the PDF. I would not be adverse to creating a slideshow, though, either. Maybe a placeholder until we get a video.

**Comment by DanVanAtta** [comment]
Okay, IMO @ZjelcoP  better to focus then on improving the tutorial or website content in other ways.

**Comment by DanVanAtta** [comment]
We have the rule book link up, hopefully that reading will be entertainment enough ;)
Otherwise, we have a number of things to focus on. I'm not opposed to working on this area more, but for the moment it seems like there is too much to do elsewhere.
