### ISSUE TITLE
Detailed troubleshooting / bug reporting faq page

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#42]
Gather debug/troubleshooting steps from the forums, consolidate to the reporting bugs / getting help page. Here is one (recent) example: http://tripleadev.1671093.n2.nabble.com/Game-won-t-start-td7591595.html#a7591708

**Comment by williamdekryger** [comment]
@DanVanAtta I had an FAQ page in progress, though if you know of other frequent questions, please tell me.

**Comment by DanVanAtta** [comment]
bug report page is up, thanks @williamdekryger
