### ISSUE TITLE
Sourceforge/Github Website Confusion

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea-game.github.io#43]
I just noticed that on the Sourceforge Site of TripleA the GitHub Repo is never mentioned.
I think the Sourceforge GitHub Website should at least link "here".

**Comment by DanVanAtta** [comment]
+1, hopefully @ron-murhammer , myself or @veqryn  will make that update soon.

**Comment by ron-murhammer** [comment]
@DanVanAtta @RoiEXLab Yeah next release I think we'll try to update links, etc.

**Comment by williamdekryger** [comment]
@ron-murhammer @DanVanAtta What are the chances that we could merely take down the Sourceforge site. It provides us nothing, as the Github site has all of the features of it and more, besides the fact that it is outdated and confusing to our users.

**Comment by ron-murhammer** [comment]
Most likely we'll just update the homepage to reference the github site and warclub after 1.9 is released.

**Comment by DanVanAtta** [comment]
The content does not bother me too much, I'm in no rush to see it deleted. IMO we could use some text in bold at the top of the sourceforge page stating that the entire project has moved to github (download link + source code). I do think we should have put a note much earlier when we migrated the source code, but water under the bridge, we can look forward to 1.9 effectively being released and almost everything being migrated out of sourceforge.

**Comment by williamdekryger** [comment]
One addition to this topic: donations. We are still sending people to Sourceforge, to this link: http://sourceforge.net/donate/index.php?group_id=44492, which looks like it goes to veqryn. Is there something we can set up for the project, so it's not tied to a particular system or admin?

I don't really care that much about this one way or the other, and in making the site obscured the link a bit because I didn't know if it even worked anymore...

**Comment by RoiEXLab** [comment]
Another thought... If we have php access to the site, we might just redirect all requests to the new site via header()

**Comment by DanVanAtta** [comment]
SF page now links to github.
PHP website is still going to be running for some time. We have a link to it in the header.
