### ISSUE TITLE
Create a Dedicated Download Page with Direct Download Links

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#6]
Instead of shelling the user out to the github page, as previously discussed between myself and @williamdekryger, let's create a dedicated download page that has direct links for the OS specific installers. For now the links will be hard coded until we can update the game engine release process to produce static download links.

**Comment by williamdekryger** [comment]
Right. This is first on my todo list, actually. Put in any things you want on that page that have not already been discussed.

**Comment by DanVanAtta** [comment]
For now, the requirements list I can think of:
- game download links
- game manual download link, or link to view the game manual (linking to it rather than downloading probably preferable)
- Mac installation instructions, notably the notes about us not having an apple developer ID and an apple using needing to allow installation from anywhere and not just content that has an apple developer ID.

**Comment by williamdekryger** [comment]
I made some mockups. First, we present the user with three large OS buttons:
![downloadoptions](https://cloud.githubusercontent.com/assets/5250014/10396569/cb42819c-6e92-11e5-8d59-15aad8e4676f.png)

When the user clicks on one, we begin the download and display installation instructions for their OS:

![macinstallationinstructions](https://cloud.githubusercontent.com/assets/5250014/10396590/f4e2f50e-6e92-11e5-98a3-c14483d8f969.png)

The text is still (obviously) a work in progress, but is that design more intuitive than the others?

**Comment by gaborbernat** [comment]
Looks great for me ;)


On 10/9/15, William DeKryger <notifications@github.com> wrote:
> I made some mockups. First, we present the user with three large OS
> buttons:
> ![downloadoptions](https://cloud.githubusercontent.com/assets/5250014/10396569/cb42819c-6e92-11e5-8d59-15aad8e4676f.png)
>
> When the user clicks on one, we begin the download and display installation
> instructions for their OS:
>
> ![macinstallationinstructions](https://cloud.githubusercontent.com/assets/5250014/10396590/f4e2f50e-6e92-11e5-98a3-c14483d8f969.png)
>
> The text is still (obviously) a work in progress, but is that design more
> intuitive than the others?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/triplea-game/triplea-game.github.io/issues/6#issuecomment-146890328


-- 
 Bernát Gábor
Student -  Budapest University of Technology and Economics - Computer
Engineering, M.Sc. - Budapest, Hungary
System Integrator - Gravity R&D | Rock Solid Recommendations - Budapest
office | 5-7 Expo ter | H-1101 | Budapest | Hungary

**Comment by gaborbernat** [comment]
As part of contract of using the install4j installer, we'll need to
add a link and a logo of install4j on the download page. Can you
extend your design with this? Maybe a little node below the three
installers?
Bernát GÁBOR

**Comment by williamdekryger** [comment]
@gaborbernat I can do that. Would you mind sending me the logo, as I can't seem to figure out which one I need to use?

**Comment by DanVanAtta** [comment]
### Button color / font:

I like the button on the far right best in terms of the background, text and image colors. I would suggest to *maybe* add a bevel or drop shadow to make it look a bit more clickable.


### Installation Instructions for each windows and Unix OS Missing

I think we need to have windows and linux installation instructions. It's a bit confusing, 3 buttons but only one set of instructions. Hopefully the windows and linux instructions will be very short, 2 or 3 lines, and simiarly we can shorten the mac instructions too.


### Whitespace on page

I would some whitespace between teh installation notes and the stuff above it. Maybe even some sort of small decorative page flourish (or we'll go 1994 style with horizontal rules!). I recommend whitespace around the installation instructions and perhaps maybe a tiny bit something extra to break up the page visually a bit better.


Version Control / Release Management of the Page

If you commit the page in beta quality, we get a really good prototype, and it's safe. Just don't link to it, comment out any links that would let people get to it. For pages we know we want, and will be creating, this is really good. It allows for additional rapid prototyping, and continuous integration. The launch is also very easily, just a matter of uncommenting some links. Feel free to push those types of changes directly to the site IMO and request feedback along the way. With our small group, we can move fast : )  and consider more slower process if things start breaking down. 


### Version numbers in the links

short answer - we can have them, but we need some javascript to read it from a file that we update when we build releases. Alternatively we drop the version numbers and look at other ways to signal when we have updated the game engine. Specifically thinking about upgrading users who will want to know the website was recently updated. 

Perhaps this could be as simple as putting the release date somewhere. Really the goal of the version number is to signal to an upgrading user that they have actually found the latest version.  If they know the game engine was updated in the last couple days, they will be able to conclude they have found a more recent version at least, if not the very latest. 

Once the download starts, it doesn't matter anymore if the version number is in the actual filename. People commonly are expected to download and launch applications, people know how to find the last thing they downloaded and to launch it. So really, the version number in the link or button I think was an old school way, and less clean way to solve the update notification problem. But worst it sacrifices the advantages of static download URLs.

Perhaps it's clear I've been thinking about static download URLs for some time now. The way it would work specifically is: release builds would trigger a second special build that produces artifacts where the version number is stripped and it pushed those to a static tag "stable". Then the download link would be static, namely:  http://github.com/triplea-game/triplea/releases/download/stable/triplea_windows_installer.exe


Game manual link or download

I would like a relatively prominent link to the rule manual. Basically so it's almost as obvious as the OS installation buttons, essentially the second most important element on the page in terms of emphasis and positioning. The third most important is probably the release date. The next is then the OS installation instructions (and hence those can be below the fold, but we do need something above the fold to let people know they are there, so perhaps having them simply start above the fold and then continue on will be plenty sufficient of a visual cue there is more content down there).

The intent is to make it very natural for people to find the rules and to start reading them while they wait for DL and install. Also it allows us to unbundle the game manual from the game engine (32MB of the game engine DL is just game manual)

**Comment by DanVanAtta** [comment]
@williamdekryger  Overall - excellent start, things are shaping up nicely.

**Comment by DanVanAtta** [comment]
@williamdekryger , crud, totally missed you would update the page with the right installation instructions. The above point above missing steps is completely irrelevant in that case.

**Comment by williamdekryger** [comment]
@DanVanAtta: I will definitely play with the button styles a bit, perhaps even resorting to three columns, each with a button at the bottom. I will also want to consider a Grunt task to update the download links across the site with a single command. Does the Github API keep track of releases and their appropriate download links? On the game manual, I can definitely link to it, quote it, embed it, whatever you like :stuck_out_tongue: (Disclaimer: I have never used Grunt, because I have never had any use for it, so I'm as new as anyone, but I think that it would really help us in many areas.)

**Comment by DanVanAtta** [comment]
A couple lines of shell could likely be used to update the game site easily. Grunt is an option,  IMO overkill for the moment though. I agree though.

The game manual, IMO let's link to it for now.

**Comment by DanVanAtta** [comment]
An idea that came to me - fitting in with the page flow style. After the install instructions are posted, user clicks a button "okay, got it", then we show rule manual stuff?

**Comment by gaborbernat** [comment]
@williamdekryger 

Here it is: http://assets-aws.ej-technologies.com/install4j-welcome-e899452710b795a2d81758653086f78e.png

I would envision a installers powered by install4j text on the bottom of the installers page, where the install4j would link to http://www.ej-technologies.com/products/install4j/overview.html. The logo could be added in there somewhere :thought_balloon:

**Comment by williamdekryger** [comment]
@DanVanAtta Such a button has occurred to me as well. It's mostly simple Javascript to hide and show elements, so should be easy.

@gaborbernat Ok, I'll work on that this weekend if I have time.

**Comment by DanVanAtta** [comment]
@williamdekryger , apologies for giving such detailed scrutiny. There is a lot to do. I realize we need to be a bit more nimble and move faster. You've shown good judgement, IMO let's favor making a more progress over hashing out every detail. So essentially please consider feedback to be advisory, we'll explicitly call out anything that is a show stopper and perhaps submit a PR ourselves to fix it.

The website is not getting much traffic right now, hardly none. The risk of doing something bad is very low, while the risk of the site stagnating for months is much greater. Let's get stuf done : )

I'm closing this, @williamdekryger submit a PR soon. The PR is mainly for the diff and paper trail, which is handy. It's a good way to organize work. If a PR being open causes problems though, merging them and moving on is okay with me right now too. My point is that if anyone reviewing really has objections then right now it's better for them to make the fixes themselves and update the code and submit a PR, contributing rather than slowing you down.

If we had a lot of traffic, it would be different. If it were game code with the established user base, it would be different as well.

**Comment by DanVanAtta** [comment]
Second thought, I'll leave closing this to @williamdekryger . Hope to see a PR soon, pls close when the time is appropriate. Sorry for the excessive emails to everyone..

**Comment by Shumaan** [comment]
We get any major work on this yet? I know it's been a couple months, and this seems like it should be a main focus of our efforts. I'd like to start something, but it seems like a lot is in limbo.

**Comment by williamdekryger** [comment]
@DanVanAtta @gaborbernat I'll be working on this as much as I can in the upcoming weeks. @Shumaan The website project has stalled quite a bit for a few months. I am back now and should be able to wrap up everything that we talked about. If you would like to contribute, that is fine, most issues are small, though this and the maps pages are the biggest ones as of yet.

**Comment by williamdekryger** [comment]
@gaborbernat The link to the install4j logo seems to be broken, and I cannot find it on my computer. Would you mind resending it, since I am in the midst of writing the download page.

**Comment by gaborbernat** [comment]
Find a detailed description of how it should look here,
https://www.ej-technologies.com/buy/install4j/openSource

There you will also find the images you need.

Thanksm

Bernát GÁBOR

**Comment by williamdekryger** [comment]
@gaborbernat Thanks.

**Comment by williamdekryger** [comment]
@DanVanAtta @gaborbernat @ron-murhammer The new download page is live. Please check it out:
http://triplea-game.github.io/download/

**Comment by ZjelcoP** [comment]
Looks nice, works well.
One issue: java. The installationpackage including java is out?
Many people hardly have any idea what java is and whether they have something like it on their computer.  Let alone what version they have or how to check that. Potential obstacle for newbies.

Also the link to download java is very easy to miss (just red letters)
Perhaps make 2 obvious buttons:
1-Download Java
2-Check my Java >>https://www.java.com/en/download/installed.jsp
Though Google Chrome doesn't allow it to run. Alternatives?

**Comment by williamdekryger** [comment]
I'm not a Windows user, so I'm probably not the expert in that area.

I can do whatever you guys suggest, though. @DanVanAtta Any thoughts on this?

**Comment by gaborbernat** [comment]
Java is now packed into the installer, sort of. If there is no Java on the users machine it will download Java from our Github assets repository and Install it silently in the background (this java is installed only for TripleA - so non system wide). The end result once through the installation the game should just work.

**Comment by ZjelcoP** [comment]
Ah great improvement! In that case i guess the installation instructions can be adjusted to this fact.

**Comment by williamdekryger** [comment]
@gaborbernat I can work on updating the instructions. Thanks!

**Comment by ZjelcoP** [comment]
Ah though i guess this is only implemented for the next version?
So 1.8.0.9 doesn't have this feature yet? In that case better leave those instructions for now.

**Comment by gaborbernat** [comment]
Indeed, however we should release 1.8.0.11 soon I think :)
On 16 Mar 2016 19:15, "ZjelcoP" <notifications@github.com> wrote:
>
> Ah though i guess this is only implemented for the next version?
> So 1.8.0.9 doesn't have this feature yet? In that case better leave those
instructions for now.

**Comment by RoiEXLab** [comment]
@DanVanAtta This can be closed IMO...
