### ISSUE TITLE
Slide show image excessive file size

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#71]
I just saw the second image in the slide show load very slowly @RoiEXLab 

One way to fix this, replace the current images in the slide show with lower resolution images appropriate for the display size. Then for each slide show image, add link that would open up the full resolution image.

**Comment by RoiEXLab** [comment]
@DanVanAtta My Problem is, that I love image quality... Quality in general (e.g. Maximum Settings in Video Games)... Somebody else has to change this :P 

I might change this in the coming week, but I'm currently not in the mood to do graphic design

**Comment by DanVanAtta** [comment]
I like quality too. But here is the problem, the extra quality is wasted. Since the image is downscaled, the image could be of lower resolution and still look identical. Page load time is very important for websites, with the faster the better.

**Comment by RoiEXLab** [comment]
@DanVanAtta what about interlacing? This is going to increase the File size, but load the images faster

**Comment by Cernelius** [comment]
Yeah, it's much too slow.

**Comment by DanVanAtta** [comment]
slow as in loading? @Cernelius ?

**Comment by Cernelius** [comment]
Yes, it is rare to find in internet a page loading as slow as the first page of triplea-game.org. My suggestion is to use jpeg 90% quality (or maybe something better) and remove a couple slideshows (down from 9 to 7).

Also, I can see it all only at +250%. At 100% like the 270BC one is cut in the middle of Sicilia and can't see the part of map under it.

Also, I believe the second slideshow should be removed, as it is redundant having a second multiple maps slide.

I would also remove Middle Earth from the lot, and possibly Great War too.

And I'm surprised there is not Total World War.

If you remove the second slide, Middle Earth and Great War, but add Total World War, you would be down from 9 to 7 slides, being the first multi slides, plus 6 picked maps (Big World, 270BC, World War II Classic, Napoleonic Empires, World At War, Total World War). 

Side notes, you should not have those stats displaying in the screenshots and the WaW map should be the latest 2.1 redrum will probably upload in a few days.

And I suggest you change the name of "Classic WW2 3rd Edition" to "World War II Classic".

**Comment by Cernelius** [comment]
![slideshow](https://cloud.githubusercontent.com/assets/19562310/18085652/533d1412-6eac-11e6-8ebb-02375324c8ed.png)

**Comment by williamdekryger** [comment]
@DanVanAtta @RoiEXLab As an original opponent of the slide show, for a few of the reasons listed [here](http://shouldiuseacarousel.com/) and a few others, I would like to find a better long-term solution, both for the load time, accessibility, and visibility of the content.

I'd prefer to replace the slider with better homepage content, maybe some more relevant or updated text and a call to action to either download TripleA, download maps, or join the community. Perhaps we can have a non-automatic slider of maps on the maps page. Sliders in general take a long time to load, and pages that take a long time to load don't help with SEO.

**Comment by RoiEXLab** [comment]
@williamdekryger Sure do whatever you think is the best for the Website!

**Comment by DanVanAtta** [comment]
slide show removed in: https://github.com/triplea-game/triplea-game.github.io/pull/94

screenshots page added (same PR): http://www.triplea-game.org/screenshots, this page is rough, could use improvements. 

Excessive image size in slide show is now no longer an issue :ballot_box_with_check:
