### ISSUE TITLE
Wrong link ...

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea-game.github.io#89]
... due to a typo:

On http://www.triplea-game.org/community/
in the text field

> TripleA is an open source project hosted on Github. Material on getting started as a map maker can be found on the Github Map Projects page

The link to the Github Map Project page is https://github.com/triplea-maps/Projects
resulting in a 404 error.

It should be https://github.com/triplea-maps/Project instead.

**Comment by DanVanAtta** [comment]
now fixed on live site, thank you
