### ISSUE TITLE
Community page Updates - remove the paragraph text

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#92]
This text:

> To chat with players and browse live games, download the game and join the lobby.
> Without the lobby, you can join the gitter discussion channel and message board

IMO we should replace it with icons, similar treatment as warclub and the other 2 icons on the community page. One for gitter, and another for the lobby.

Here is a screenshot of the page for context:
![example](https://cloud.githubusercontent.com/assets/12397753/18192336/3ae95924-7088-11e6-9e40-fa585e3d7ba5.png)

**Comment by williamdekryger** [comment]
Alright, I'm game to see what you have in mind. I'm not sure exactly what you want in its place, though I do believe there should be a bit of text there to introduce the page.

**Comment by DanVanAtta** [comment]
The community page was updated some time back. Closing for now, new suggestions can take a fresh look (and submit a new issue)
