### ISSUE TITLE
Change website color palette to match warclub?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#95]
Thoughts on having the github.io website use the same general CSS  as warclub? The motivation there  would be to make the two more similar so we can start blending the two sites together.

My thoughts are we should start by adopting first the same font and color palette.  The two sites are different, so to me it would make sense that they still stay somewhat visually distinct.

**Comment by williamdekryger** [comment]
Moving discussion to https://github.com/triplea-game/triplea/issues/1070 so that we can get an idea of what is happening, and some more opinions. Will come back here to decide specifics for the website itself.

**Comment by DanVanAtta** [comment]
I think the question still remains, should we update the github.io website to match the CSS of warclub? We're not going to be merging/transitioning websites just yet anytime soon. The color/theme match woudl at least make the websites seem more cohesive.

**Comment by DanVanAtta** [comment]
Closing for now, topic is not very current anymore.
